Add Roomservice
Squashed commit of the following:

commit 92ad4f701c2bfb78a078f7956a5f6438480efa9d
Co-authored-by: Alex Cruz <du.alexcruz@gmail.com>
Date: Sep 8, 2018

    Add option to pull pixel gapps conditionally from gitlab

This adds in a very simple but efficient way to include pixel gapps
into devices like the Marlin, Taimen and Nash. Our Gapps package can
not be hosted on Github due to file limits, so this adds in the gapps
package conditionally for those devices.

- Checks for the existence of the pixelgapps repo so we're not attempting
to clone the repo every time.

- Used subprocess to clone repo in order to avoid compatibility issues

- Checks for pixelgapps inheritance line in du.mk to determine whether to
clone the pixel gapps or not. Thanks @DeviousFusion for the idea!

- Add pixel gapps to local manifest so we can pull in updates in a repo sync

Change-Id: I5c2980cf308b563a706b24bd363c10b9946519b8

commit 164a2088da1453d598d5bd0038a62a6867ea53e4
Co-authored-by: rc420head <dennislebhardt79@gmail.com>
Date:   Fri Aug 30 12:47:38 2019 -0500

    make it AquariOS

commit 5b5d8ede784c37f1d2ab0993d2db6326117d95b1
Co-authored-by: Alex Cruz <du.alexcruz@gmail.com>
Date:   Sun Sep 17 16:57:01 2017 -0400

    Fix file permissions for roomservice

commit 0890f6fb237837c64f2a8e20d849bedeb68dc601
Co-authored-by: Jmz <jmztaylor@gmail.com>
Date:   Sun Sep 17 16:34:53 2017 -0400

    Add option for api_token to prevent getting rate limited

    Create file ~/api_token
    Go to github and get personal access token in settings
    Add to api_token file without line breaks or spaces

    Change-Id: I998f910b6ac63df38363520b200874a86da37c10

commit 30155ca39ef81d663450dc5b62edb3de049f8e81
Co-authored-by: Diogo Ferreira <defer@cyanogenmod.com>
Date:   Sun Sep 17 16:29:43 2017 -0400

    Add lightweight dependencies to repositories

    Roomservice can already fetch your cm_<device> without the need for a
    manifest entry.

    However, when working with common repositories, there is no way of
    actually fetching them without adding to the manifest. This patch
    introduces a lightweight dependency system. Each repository can have a
    cm.dependencies in the following json format:

    [
      {
        "repository": "repository_name_on_cm_organization"
        "target_path": "target/path"
      },
      ...
    ]

    For instance, for cm_anzu I need android_device_semc_msm7x30-common and
    android_device_semc_mogami-common. I would add both to cm.dependencies
    as follows:

    [
      {
        "repository": "android_device_semc_msm7x30-common",
        "target_path": "device/semc/msm7x30-common"
      },
      {
        "repository": "android_device_semc_mogami-common",
        "target_path": "device/semc/mogami-common"
      }
    ]

    Roomservice would then fetch the anzu repository, parse the dependency
    files and add/fetch/sync these additional repositories if they don't
    exist already.

    This also adds pretty printing to the output xml.

    Change-Id: I9cc847adfc717a06439bc6094213ed6492343158

    roomservice: Add branch support to cm.dependencies

    Allow the cm.dependencies entries to provide an optional "branch" for
    the repository dependencies. Added to fully support
    http://wiki.cyanogenmod.com/wiki/Integrated_kernel_building

    Change-Id: I35b51920d296afa329411af6172c7bd9aeef4af8

    roomservice: Fill in dependencies for already-deployed repositories

    Change-Id: I01fd408c9c4bfa78097c7f848b2556d2b2b180f3

    roomservice: Extend dependency-checks to devices in main manifest

    CM currently keeps devices inherited from AOSP in the main manifest,
    so take that into account as well when checking device paths

    Change-Id: I9663f283617f237428b4eaa0cd60b5de2b86a7b9

    make compatible with github v3 api

    Change-Id: Iff6f1f9099cdc5d2b49e04000b5fe3d04aa5d7e4

    Fixed build for full-eng

    Previously
    Traceback (most recent call last):
      File "build/tools/roomservice.py", line 153, in <module>
        repo_path = get_from_manifest(device)
    NameError: name 'device' is not defined

    ** Don't have a product spec for: 'full'
    ** Do you have the right repo manifest?

    Now
    ============================================
    PLATFORM_VERSION_CODENAME=REL
    PLATFORM_VERSION=4.0.4
    TARGET_PRODUCT=full
    TARGET_BUILD_VARIANT=eng
    TARGET_BUILD_TYPE=release
    TARGET_BUILD_APPS=
    TARGET_ARCH=arm
    TARGET_ARCH_VARIANT=armv7-a
    HOST_ARCH=x86
    HOST_OS=linux
    HOST_BUILD_TYPE=release
    BUILD_ID=IMM76L
    ============================================

    Change-Id: Ib513705aba9a7a52a971ab64102ecbe9fddfb97a

    roomservice: Bump github request per_page to 100

    Change the number of repos per page from the default 30
    to 100.

    We seem to be hitting the rate limit on the jenkins server.

    Change-Id: Ie733feaa0414cbfebb7efcfc1e24d94e1e466d1b

    roomservice: Add support for netrc

    Change-Id: I1f5e11e40125abd0c4e4c8d8294d4fc09bfdc30a

    roomservice: Handle missing netrc file

    Change-Id: If981fe79dc3e2191434301239b0cd585be8b4730

    roomservice.py: Verbose error when a branch is missing.
    Also add ROOMSERVICE_BRANCHES environment variable to use fallback branches.

    Change-Id: I3c2b1d79fc185c1f1e1d658e5ca4f78e688780e2

    roomservice.py: Fixups around fallback branches not being used by dependencies when ROOMSERVICE_BRANCHES is defined.

    Change-Id: Ifb42a023cae5f62ac8f9cf7832125b91b431169c

    roomservice: Allow following up tag references

    This is now needed for release builds

    Change-Id: I8c5f87341059b3b15ee853312b71df73790ad0d8

    build: local_manifest.xml deprecated, use local_manifests

    Patch Set 2:- Use roomservice.xml instead of cm.xml.

    Change-Id: I3d8a6ef3907b92808662cbba912cea5ed38d0bde

    Fix fallback branch search in roomservice

    If you provided a fallback branch to roomservice via the
    ROOMSERVICE_BRANCHES environment var the branch search would fail
    if the device repo had any tags.

    Fixed this by appending the tag search results to the branch
    search results instead of overwriting them

    Change-Id: I73a11af1500bd04e346f08ec3f83454502f3a169

    roomservice: Fix wrong assumption about path of active manifest

    Change-Id: Id740ff4b848e6ccbfd658be4846197b8ca519237

    roomservice: When validating the presence of a repo, check main manifest too

    Change-Id: If680536484074b473458723d93e783d074d7f669

    roomservice: Bump devices per page to 200

    Limit was reached again when attempting to
    lunch various projects, such as steelhead.

    Change-Id: I2f3b9705e07e1e47b86857aeb383cf7c99fcdbdc
    Signed-off-by: William Roberts <bill.c.roberts@gmail.com>

    roomservice: Fix assumptions about the branch naming

    We can't just split from the last slash anymore, since we're using
    those to distinguish the stabilization branches

    Change-Id: Ia175dd317f508e99b275b56e9c83bd4729a75ddb

    roomservice: Add recursive dependencies

    Dependency repositories can now have dependencies themselves

    Change-Id: I33a28709170da52bc98f4a62387927e3a11b2450

commit 433ab9c2a517582bd024cc20edc77aff777d6356
Co-authored-by: Erik Castricum <git@cas-online.nl>
Date:   Sat Jul 29 18:51:03 2017 +0200

    Force sync dependencies

    Jenkins builds stock variant for choose from device repos
    that are in another organization. This will cause sync
    faillure on fetching dependencies.
    Using "--force-sync" flag will solve this issue

    Change-Id: Icff807ba4df5477dd2d8b1d7119bba9175c86425

commit 9ed9792d219d740df41b43d4566300699df0a75f
Co-authored-by: Humberto Borba <humberos@gmail.com>
Date:   Sat Sep 10 14:30:27 2016 -0300

    Fix roomservice during project validation

    Remove roomservice only if there is value to compare.

    Change-Id: Iefef90ba21c923243a6eff37229301f202988d9a

commit 28d042919e1039b39a1f76af3c85d9a0ef0548ad
Co-authored-by: Humberto Borba <humberos@gmail.com>
Date:   Fri May 6 17:20:02 2016 -0300

    Create manifest entries from common repos

    With this change we will be able to read omni.dependencies from common repositories.

    Change-Id: Ic66ceead3601263df0c0e181a45b9ef7e7a32b77

commit 0a6b8b11e0e4fd0fa26771ae7331f186d2f03cc9
Co-authored-by: Humberto Borba <humberos@gmail.com>
Date:   Fri May 6 14:43:39 2016 -0300

    Handling URLError exception during fetch device process

    BEFORE:

    humberos@fedora:/android/omni-6.0$ bib leo
    WARNING: Trying to fetch a device that's already there
    Traceback (most recent call last):
      File "build/tools/roomservice.py", line 319, in <module>
        fetch_dependencies(device)
      File "build/tools/roomservice.py", line 275, in fetch_dependencies
        fetch_device(device)
      File "build/tools/roomservice.py", line 287, in fetch_device
        git_data = search_gerrit_for_device(device)
      File "build/tools/roomservice.py", line 71, in search_gerrit_for_device
        response = urllib.request.urlopen(git_req)
      File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python2.7/urllib2.py", line 431, in open
        response = self._open(req, data)
      File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
        '_open', req)
      File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/usr/lib64/python2.7/urllib2.py", line 1242, in https_open
        context=self._context)
      File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno -5] No address associated with hostname>

    AFTER:

    humberos@fedora:/android/omni-6.0$ bib leo
    WARNING: Trying to fetch a device that's already there
    WARNING: No network connection available.

    Change-Id: I18950704c5b7d13553374611d164c2464c1ceab2

commit 6970146622897f7ec473a7b87ba7fa36ad74d1a8
Co-authored-by: Jake Whatley <jacob.whatley91@gmail.com>
Date:   Tue Feb 9 09:57:20 2016 -0500

    Dynamically remove duplicate projects from roomservice manifest

    Change-Id: Idf4da69ca829fcd59d5264b05b9ed1c37d0195f8

commit 59f20510c1c80780404d45b59b7294e20506cea3
Co-authored-by: maxwen <max.weninger@gmail.com>
Date:   Sat Jan 23 23:07:07 2016 +0100

    Catch revision changes for existing entries

    delete existing roomservice file and restart in that case

    Change-Id: I2adc62da01fb75cd8ee5b13b5864043fb2594d0f

commit 14c1dd3eb0176e4a287530a88eeb5e9c064396db
Co-authored-by: maxwen <max.weninger@gmail.com>
Date:   Wed Jun 10 22:13:47 2015 +0200

    Support same repo using different path and revision

    Change-Id: Ifd47cbeab2ca7e99a117883e3a3ecb880581e110

commit c447f62f9564b0f7df6beb69b4ae96bee432868a
Co-authored-by: Benjamin Cheng <lolzballs.mc@gmail.com>
Date:   Mon Dec 8 22:58:42 2014 -0500

    Fix grammar error in roomservice

    - Only add xml files in local_manifests

    Change-Id: Ia132acddd2761ec4c1bea7fb510e3bea306ea9fc

commit ddd6e0ebd353fab7e15f2be38bdb3fdde19a2a07
Co-authored-by: Jens Andersen <jens.andersen@gmail.com>
Date:   Tue Sep 30 23:39:46 2014 +0000

    Search gerrit instead of github

    * Search for devices using gerrit api instead of github
    * Minor cleanups & fixes

    Change-Id: I54fc898f3c773f79936568818996ae5fab11e491

commit c66adb958f0fdad6ccc9bec31fa4e794046e2e57
Co-authored-by: Alex Cruz <du.alexcruz@gmail.com>
Date:   Wed Nov 5 00:46:24 2014 -0500

    Change default remote and branch

    Change-Id: I95e054bd39a3c38ab5e656d0a3c06c4015aa8a15

commit 2dc802958021e3ea2cacd185f2433d06d0463489
Co-authored-by: mithun46 <mithuncursed4eva@gmail.com>
Date:   Thu Dec 12 01:59:05 2013 -0500

    Urgent: add "+fork:true"

    Enable a device config to be found on github if it was forked

    Change-Id: Ic63f82b9ed754dcba17725f5aa75d0011896b09c

commit 76273522d152289ebae20101b6b5cd79293ad23d
Co-authored-by: Dominik Marszk <dmarszk@gmail.com>
Date:   Sun Nov 3 15:02:27 2013 +0100

    Add -f and --no-clone-bundle flags to repo sync

    Suppress scary-looking common warnings during resolving.

    Change-Id: I4337ec95992ad68ff4471b0d0b7346e933269503

commit a0fc8f7c54b3b26eb56e288586bb58abce7c8a4c
Co-authored-by: Andrew Dodd <atd7@cornell.edu>
Date:   Sat Dec 7 11:05:37 2013 -0500

    Fix handling of devices with _ in their name

    Currently, roomservice takes every _ in the device tree name and
    replaces it with /

    Instead, strip the device name (such as pollux_windy) from the repo
    name before replacing _ with / and then append it again when we're done

    Change-Id: Ieabe85ecd8829c959a7296e5cd73f577879c4ffc

commit fc0f4898b0b94576bd60bf7351e9f688010f98dd
Co-authored-by: cybojenix <anthonydking@gmail.com>
Date:   Sun Nov 10 19:10:32 2013 +0400

    The search api is out of preview now

    Change-Id: I95f088daf8537784caf774ad6863037f7019f22d

commit f927950ca5af51caf022b7b8718ea8c3857d4c21
Co-authored-by: Dominik Marszk <dmarszk@gmail.com>
Date:   Sun Nov 3 14:13:12 2013 +0100

    Fix os.path.isdir calls

    Apparently on some Python installations
    it throws exception instead of returning False.

    Change-Id: I9d901e3260bab411cf3466346c421594f0922562

commit 59aa2cc79199424250b4a1f2fa6c84dd58752c0e
Co-authored-by: Jens Andersen <jens.andersen@gmail.com>
Date:   Wed Oct 23 21:46:02 2013 +0000

    Support fetching dependencies even if device tree fails.

    This is required when device tree depends on dependencies to lunch.

    Change-Id: If62cd9777caf768f8070570ca0835052645c6b20

commit 942206edf194bde11ddafbdded56eb85cdfc9f63
Co-authored-by: cybojenix <anthonydking@gmail.com>
Date:   Sun Sep 17 16:05:20 2017 -0400

    Add in roomservice

    This is a new implementation of roomservice
    use the new github search api to reduce the memory footprint, and make it less processor intensive
    allow for unofficial devices to fetch dependencies. just specify your github organization

Change-Id: If62cd9777caf768f8070570ca0835052645c6b20